# Project Name
TARGET = GateInput

APP_TYPE = BOOT_SRAM

# Sources
CPP_SOURCES = GateInput.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
LDSCRIPT=alt_sram.lds

include $(SYSTEM_FILES_DIR)/Makefile
